info:
  app.name: eagle-eye-licensing-service
  company.name: www.zzz.com
  build.artifactId: @project.artifactId@
  build.version: @project.version@

eureka:
  instance:
    prefer-ip-address: true
    instance-id: eagle-eye-licensing-service
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://192.168.0.129:8761/eureka/

logging:
  config: classpath:log4j2.properties