info:
  app.name: eagle-eye-licensing-service
  company.name: www.zzz.com
  build.artifactId: @project.artifactId@
  build.version: @project.version@

eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost
#    instance-id: eagle-eye-licensing-service
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
#      defaultZone: http://192.168.0.129:8761/eureka/
      defaultZone: http://192.168.0.140:8761/eureka/

#logging:
#  config: classpath:log4j2.properties

#Setting the logging levels for the service
logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.thoughtmechanix: DEBUG

server:
  port: 9009


spring:
  cloud:
    stream:
      bindings:
#        input:
#          destination: orgChangeTopic
#          content-type: application/json
#          group: licensingGroup
        inboundOrgChanges:
          destination: orgChangeTopic
          content-type: application/json
          group: licensingGroup
      kafka:
        binder:
#          zkNodes: localhost
          zkNodes: 192.168.0.140
#          brokers: localhost
          brokers: 192.168.0.140