server:
  port: 5555

eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost
#    instance-id: ${eureka.instance.ip-address}:${eureka.instance.appname}:${server.port}
#    appname: zuul-service
#    ip-address: 192.168.0.129
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://192.168.0.129:8761/eureka/

zuul:
  #  host:
  #    socket-timeout-millis: 60000
  #    connect-timeout-millis: 60000
  prefix: /api
  routes:
    organization:
      path: /organization/**
      service-id: organizationservice
#      url: http://192.168.0.129:8085
#  routes:
#    organizationservice: /organization/**
    licensingservice: /licensing/**
#  auth config for passing Authorization
  sensitive-headers: Cookie, Set-Cookie

management:
  security:
    enabled: false

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 600000

ribbon:
  ReadTimeout: 600000
  ConnectTimeout: 600000
  maxAutoRetries: 1
  maxAutoRetriesNextServer: 3
  okToRetryOnAllOperation: true
  eureka:
    enabled: true

logging:
  config: classpath:log4j2.properties