server:
  port: 8901
  context-path: /auth

management:
  security:
    enabled: true

info:
  app.name: eagle-eye-authentication-service
  company.name: www.zzz.com

eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://192.168.0.129:8761/eureka/