#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
#    username: root
#    password: 123456
#    driver-class-name: com.mysql.jdbc.Driver
server:
  port: 8085

info:
  app.name: eagle-eye-organization-service
  company.name: www.zzz.com

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${eureka.instance.ip-address}:${eureka.instance.appname}:${server.port}
    appname: eagle-eye-organization-service
    ip-address: 192.168.0.129
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://192.168.0.129:8761/eureka/